
Vagrant.configure("2") do |config|

 # mysql server

   config.vm.define "server.mysql" do |db|
     db.vm.box = "ubuntu/xenial64"
     db.vm.network "private_network", ip: "10.1.1.30"
     db.vm.hostname = "server.mysql"

     db.vm.provider "virtualbox" do |v|
       v.memory = 2024
     end

     db.vm.synced_folder "/Users/irvingr/_GRABS/arch-DEV-vm/_vm-bin-share", "/host"
   end

end
